### ISSUE TITLE
TypeError: 'odict_keys' object does not support indexing

### ISSUE THREAD

**Issue by perseus-me** [idlesign/makeapp#3]
При создании нового проекта получаю следующий трейсбэк:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/makeapp", line 11, in <module>
    load_entry_point('makeapp==0.9.0', 'console_scripts', 'makeapp')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/makeapp/cli.py", line 8, in <module>
    from makeapp.appmaker import AppMaker
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/makeapp/appmaker.py", line 25, in <module>
    class AppMaker(object):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/makeapp/appmaker.py", line 58, in AppMaker
    default_vcs = VCS.keys()[0]
TypeError: 'odict_keys' object does not support indexing
```
python3.6

лечится вот так: `default_vcs = list(VCS.keys())[0]`

**Comment by idlesign** [comment]
Thank you for the report. Fixed in 0.9.1

Pull request is just a couple of clicks away %)
